---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: docker-ce
    state: present

- name: Install python
  block:
    - name: Install system packages
      become: true
      package:
        name:
          - python-setuptools
          - python3
          - python3-pip
        state: present

- name: Install docker
  pip:
    name: docker
    state: present


- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true
